package com.example.spring_mvc_crud.entity;

import jakarta.persistence.*;

// `@Entity`: marks the class as JPA entity. without it the class will not mapped to db table
//            because Hibernate will not recognize this class as entity
// `@Table` & `@Column`: used to map the class and its field to the table and its columns.

@Entity
@Table(name = "employee")
public class Employee {
    @Id // add this annotation to primary key column that in db
    @GeneratedValue(strategy = GenerationType.IDENTITY) // means this column is auto generated by db
    @Column(name = "id")
    private int id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "email")
    private String email;

    /* Constructors */

    public Employee() {} // No-argument method is required in JPA.

    public Employee(String firstName, String lastName, String email) {
        // "id" is auto generated. so don't include it.
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    /* Are Getters & Setters Required? Yes
        - It is required for binding process and in Model. not strictly mandatory in general.
          but will face an exception because you don't include it. so, please include it and shut up. */


    /* Getters */

    public int getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public String getLastName() {
        return lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    /* Setters */

    public void setId(int id) {
        this.id = id;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
